### ISSUE TITLE
Use correct license and SCM in the RI pom

### ISSUE THREAD

**Issue by ctubbsii** [amaembo/jsr-305#27]
I can't tell if this is the canonical location for jsr-305 now, but it appears to be the location from which this project is deployed to Maven Central. Is that correct, or is this a fork of another, more canonical location?

If this is the correct location, then this location should be used in the SCM section of the pom.xml.

The license is also listed as Apache, but that appears to be incorrect. The actual license looks like it's BSD (see the LICENSE file).

**Comment by amaembo** [comment]
Pull-request is welcome.
