### ISSUE TITLE
Suggest moving project

### ISSUE THREAD

**Issue by ctubbsii** [amaembo/jsr-305#28]
I looked all over to see if there were any other repos on GitHub more active than this one, for the "current" location of jsr305 code, and it looks like this one is it. I recommend transferring the repo to https://github.com/findbugsproject/ so it can be more easily found, especially since the maven coordinates indicate it's being published to Maven Central in a way that it's related to Findbugs.

**Comment by amaembo** [comment]
Hello! You are free to contact findbugsproject administration to move it there. I don't have rights to create projects under findbugsproject (otherwise I would do it by myself).

**Comment by ctubbsii** [comment]
Oh, interesting. I assumed that you were in content with them already, because of the groupId under which this was being pushed to Maven Central. I'll try to reach out to them and see if they'll permit the project in their space, carrying you along as a committer since you've been maintaining it here. Even if that doesn't happen, fixing #27 should help users find the project here. (I'll put together a PR for that one soon.)
