### ISSUE TITLE
A contrary for @Immutable

### ISSUE THREAD

**Issue by mbrinkma** [amaembo/jsr-305#34]
I would like to explicitly mark some classes to be @ThreadSafe AND @Mutable. This is currently not possible (there is only an @Immutable-annotation).

**Comment by amaembo** [comment]
Hello! JSR-305 is dead. I doubt it will be developed anymore. I'm not the original author, I just salvaged it from dying code.google.com. Please check other annotation packs like Checker Framework.

**Comment by mbrinkma** [comment]
Hello! 

Thanks for the info. Really sad, I liked JSR-305 a lot.

Ok, I will "bite the bullet" and migrate to Checker-annotations. (Or SpotBugs? Or ErrorProne?)

br
Michael

**Comment by amaembo** [comment]
Alternatively you can fork the repo and maintain it by yourself. Open source, you know :-)

**Comment by mbrinkma** [comment]
Yes, but according to https://github.com/google/guava/issues/2960 just by creating some "javax.annotations" by my own I open a "can of worms":

"
F. JAVA TECHNOLOGY RESTRICTIONS. You may not create, modify, or change the behavior of, or authorize your licensees to create, modify, or change the behavior of, classes, interfaces, or subpackages that are in any way identified as "java", "javax", "sun", “oracle” or similar convention as specified by Oracle in any naming convention designation.
"

That sentences scares me  a lot :-)
